/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIBootScreens;

import backend.TextRenderer;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import backend.DisclaimerBoxThread;
import javax.swing.JButton;
import javax.swing.JCheckBox;

/**
 *
 * @author darrenl
 */

// WHEN ALL BOXES CHECKEd OPEN UP LOGIN
public class Disclaimer extends javax.swing.JFrame {

    /**
     * Creates new form Disclaimer
     */
    public Disclaimer() {
        initComponents();
        printDisplayText("Data\\NDA.txt");
        DisclaimerCheckBoxThread();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        NDA = new javax.swing.JCheckBox();
        LossOrHarm = new javax.swing.JCheckBox();
        Death = new javax.swing.JCheckBox();
        Painetc = new javax.swing.JCheckBox();
        Agree = new javax.swing.JButton();
        Agree2 = new javax.swing.JButton();
        Agree3 = new javax.swing.JButton();
        Agree4 = new javax.swing.JButton();
        Agree5 = new javax.swing.JButton();
        LossOfLimbs = new javax.swing.JCheckBox();
        Censorship = new javax.swing.JCheckBox();
        ToHaveAGoodTime = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayTextArea.setColumns(20);
        DisplayTextArea.setRows(5);
        jScrollPane1.setViewportView(DisplayTextArea);

        NDA.setText("Our NDA");
        NDA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NDAItemStateChanged(evt);
            }
        });
        NDA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NDAStateChanged(evt);
            }
        });
        NDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NDAMouseClicked(evt);
            }
        });

        LossOrHarm.setText("Loss Or Harm");

        Death.setText("Death");

        Painetc.setText("Pain and Possible Murder");

        Agree.setText("AGREE");

        Agree2.setText("AGREE");

        Agree3.setText("AGREE");

        Agree4.setText("AGREE");

        Agree5.setText("AGREE");

        LossOfLimbs.setText("Loss of Limbs");
        LossOfLimbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LossOfLimbsActionPerformed(evt);
            }
        });

        Censorship.setText("Censorship");

        ToHaveAGoodTime.setText("TO HAVE A GOOD TIME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agree4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Agree5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NDA)
                            .addComponent(LossOrHarm)
                            .addComponent(Death)
                            .addComponent(Painetc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agree2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agree3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LossOfLimbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Censorship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ToHaveAGoodTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NDA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LossOrHarm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Death)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Painetc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LossOfLimbs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Censorship)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(ToHaveAGoodTime)
                .addGap(43, 43, 43)
                .addComponent(Agree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agree2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agree3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agree4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agree5)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LossOfLimbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LossOfLimbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LossOfLimbsActionPerformed

    private void NDAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NDAStateChanged
        
        
        
    }//GEN-LAST:event_NDAStateChanged

    private void NDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NDAMouseClicked

        
    }//GEN-LAST:event_NDAMouseClicked

    private void NDAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NDAItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NDAItemStateChanged
        private void printDisplayText(String File) {

        TextRenderer renderer = new TextRenderer(DisplayTextArea, 10, File);

        Thread thread = new Thread(renderer);
        
        thread.start();
        

       
    }
        
    private void DisclaimerCheckBoxThread(){
        DisclaimerBoxThread DisclaimerBoxs = new DisclaimerBoxThread(NDA, LossOrHarm, Death, Painetc, LossOfLimbs, Censorship, ToHaveAGoodTime, Agree,Agree,Agree2,Agree4,Agree5);
        
        Thread DisclaimerBoxThread = new Thread(DisclaimerBoxs);
        
        DisclaimerBoxThread.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disclaimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agree;
    private javax.swing.JButton Agree2;
    private javax.swing.JButton Agree3;
    private javax.swing.JButton Agree4;
    private javax.swing.JButton Agree5;
    private javax.swing.JCheckBox Censorship;
    private javax.swing.JCheckBox Death;
    private javax.swing.JTextArea DisplayTextArea;
    private javax.swing.JCheckBox LossOfLimbs;
    private javax.swing.JCheckBox LossOrHarm;
    private javax.swing.JCheckBox NDA;
    private javax.swing.JCheckBox Painetc;
    private javax.swing.JCheckBox ToHaveAGoodTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
